PATH_NOT_FOUND = "The system cannot find the path specified."
PAUSE_TEXT = "Press any key to continue . . . "
ENV_VAR_UNDEFINED = "Environment variable name not defined"
SYNTAX_INCORRECT = "The syntax of the command is incorrect."
SURE = "Are you sure (Y/N)?"
DELETE = "Delete (Y/N)?"
