cd %temp%
echo %errorlevel%
echo %cd%
mkdir some-temp-file-name
echo %errorlevel%
pushd some-temp-file-name
echo %errorlevel%
echo %cd%
mkdir parent
echo %errorlevel%
pushd parent
echo %errorlevel%
echo %cd%
mkdir child
echo %errorlevel%
pushd child
echo %errorlevel%
echo %cd%
